### ISSUE TITLE
ValueError: size of reduced grid does not match number of data values

### ISSUE THREAD

**Issue by srepmub** [jswhit/pygrib#215]
hi,

running the following for a specific ECMWF forecast data file:

```
    for grb in grbs:
        print(grb)
        print(grb.gridType)
        print(grb.gaussianGridName)
        print(grb.values)
```

I'm getting the following traceback:

```
Traceback (most recent call last):
  File "/home/srepmub/s4l2-processors-st/modeldata/plot_ecmwf.py", line 17, in <module>
    print(grb.values)
  File "src/pygrib/_pygrib.pyx", line 766, in pygrib._pygrib.gribmessage.__getattr__
  File "src/pygrib/_pygrib.pyx", line 1172, in pygrib._pygrib.gribmessage.__getitem__
  File "src/pygrib/_pygrib.pyx", line 1279, in pygrib._pygrib.gribmessage._reshape_mask
  File "src/pygrib/_pygrib.pyx", line 32, in pygrib._pygrib._redtoreg
ValueError: size of reduced grid does not match number of data values
```

when using the eccodes bindings directly, I can get 'values' out no problem.

could this be an indication there is something wrong with the data file, or of a bug in pygrib..?

**Comment by srepmub** [comment]
oooh.. using grb.expand_grid(False) avoids the issue. perhaps the valueerror could hint a bit at this? (TBH I haven't even checked the documentation, so possibly just my bad..)
