### ISSUE TITLE
pygrib open does not allow io.BufferedReader object

### ISSUE THREAD

**Issue by Tamburasca** [jswhit/pygrib#259]
According to the version 2.1.5 release
* allow pygrib.open to take an io.BufferedReader object as an argument

reading BufferedReader objects is supposed to work now. I got version 2.1.6, though, and I reckoned that the following code should work then as well:

```python
import requests
import io
import pygrib

response = requests.get("https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20241123/00/atmos/gfs.t00z.pgrb2.0p25.f000")
response.raise_for_status()

f = io.BytesIO(response.content)
buffer_io = io.BufferedReader(f)
fsss = pygrib.open(buffer_io)
for item in fsss:
    print(item)
 ```
 However, I get an error
 Traceback (most recent call last):
  File "/home/ralf/pycharm-projects/testStuff/gfs/gfs_http_download.py", line 18, in <module>
    fsss = pygrib.open(buffer_io)
  File "src/pygrib/_pygrib.pyx", line 338, in pygrib._pygrib.open.__cinit__
io.UnsupportedOperation: fileno

Is there something I may have disregarded?

Thanks.

**Comment by kleinux** [comment]
I am getting the same error when using version 2.1.6 In my case I am trying to read from an Azure storage acount like 

```
open_file_client = container_client.get_file_client(raw_filepath)
open_file_bytes = io.BytesIO()
open_file_client.download_file().readinto(open_file_bytes)
g = pygrib.open(open_file_bytes)
buffer_io = io.BufferedReader(open_file_bytes)
g = pygrib.open(buffered_io)
```

This raises an UnsupportedOperation: fileno error

**Comment by jswhit** [comment]
@noritada any idea what's going on here?

**Comment by jswhit** [comment]
@kleinux and @Tamburasca - PR #273 was merged, so you could try it again with github master and your examples should now work.  

EDIT:  I've released wheels for 2.1.8 that include this fix.

**Comment by Tamburasca** [comment]
@jswhit Thanks for your fix. In the meantime I downloaded to a temp files, which works fine to date.
