### ISSUE TITLE
pygrib grb.keys() return keys that can't be used.

### ISSUE THREAD

**Issue by akrherz** [jswhit/pygrib#94]
Consider this example using the `test.grb` in the code repo
```python
import pygrib

grb = pygrib.open('test.grb')[1]
for key in grb.keys():
  print(grb[key])
```

After dumping a few values, it errors with
```
Traceback (most recent call last):
  File "ex.py", line 5, in <module>
    print(grb[key])
  File "pygrib.pyx", line 1205, in pygrib.gribmessage.__getitem__
    raise RuntimeError(grib_get_error_message(err))
RuntimeError: b'Key/value not found'
```

I would expect `keys()` to return valid keys that can be looked up against the grib message.  Thanks for your efforts on this library.

**Comment by jiancan9935** [comment]
grbs = pg.open(file_name)
    for grb in grbs:
        for key in grb.keys():
            print(grb[key])

**Comment by dobriai** [comment]
Yes, it still does that. And to be specific, it does so for the keys `analDate` and `validDate` only! They seem to be treated specially, indeed:

https://github.com/jswhit/pygrib/blob/e097167c8ee8ed98c84efa55352e29015f849cf8/src/pygrib/_pygrib.pyx#L1053

Not sure why.

Interestingly, something like `grb.analDate` works fine. Thus the following snippet can be used as a workaround:
```
eval(f'grb.{key}')
```
or even
```
pprint.pformat(eval(f'grb.{key}'))
```
perhaps.

In any case, it is annoying to have to do that. I wish the authors would fix this or explain why it cannot be fixed, as a consolation :-)
